### PR TITLE
Set capital_cost of lines in k means clustering to weighted average.

### PR DESCRIPTION
**Pull request by ClaraBuettner**

### CODE REVIEW

**Review by ulfmueller — CHANGES_REQUESTED** [review]
I am pretty sure the new implementation does the same as the old...

**Comment by ClaraBuettner** [comment]
I changed the capital_cost calculation, it now considers line_length factor (to have equal prices per km) and only respects extendable lines. 
The s_nom_extendable.any() did what we needed and chooses True if one of the values is True.

**Comment by ulfmueller** [comment]
Nice! Will you change the [line](https://github.com/openego/PyPSA/blob/feature/costs_kmeans/pypsa/networkclustering.py#L206) so that it sets the clustered line always extendable once one of the original lines is extendable = True ?

**Comment by ClaraBuettner** [comment]
That's what the function numpy.any() already does, I tested it and read the describtion.

**Pull request merged**
