### PR TITLE
enable clustering on results

### PR DESCRIPTION
**Pull request by ulfmueller**
The changes enable to use the k-means clustering also for a already calculated network i.e. including results.

### CODE REVIEW

**Comment by lukasoldi** [comment]
I guess the changes do not in any way influence the calculation of a non-existing network since p_nom_opt and state_of_charge etc. are not set by then, right?

**Comment by ulfmueller** [comment]
That was of course my intention and my testing did not show any problems. Anyhow I would really appreciate it if someone would test it again just to be sure that it does the same as before.

Exactly p_nom_opt and state_of_charge are result values which are not set by then!

**Comment by ulfmueller** [comment]
@BartelsJ Have you tried this out and could give an approval?

**Comment by BartelsJ** [comment]
Sorry for the late answer. I am struggling with the reuse of a former network. I assumed to load it via network.import_from_csv_folder() function, but getting error messages continuously. Could you provide a test setting? For a short-term approve, maybe @lukasoldi (again) or @wolfbunke can review this again.

**Comment by ulfmueller** [comment]
if you use network.import_from_csv_folder() you probably have to delete the first , in the two lines in the network.csv. Then it should work. Not very convenient and definitely worth an issue (we had one back in the days...).

**Review by lukasoldi — APPROVED** [review]
Tested it, works!

**Pull request merged**
